# The importance of questions and sources of data

## Questions
Any question to be asked of biodiversity data should be put as simply and succinctly as possible. With the number of different subject areas and techniques used, analyses can quickly become complex.

## Taxonomies
It is important to be aware of likely taxonomic anomalies prior to working within a region. Checklists are very important, especially if working over several regions / countries. Whilst there are many things that will automatically look for the validity of a name they do not check for the validity of that species occurrence. For example *Sphagnum auriculatum* and *S. denticulatum* are both valid names. *S. auriculatum* is the currently accepted species in Europe but in the British Isles, Ireland and the Netherlands *s. denticulatum* is the most recorded taxa. Using data from across the European region without acknowledging this disagreement would impact the results of any research undertaken. For taxa which are known to be capable of dispersing great distances (eg birds) this becomes even more difficult especially when using community sourced data.

For Sweden there is an agreed taxonomy for species accesible through [https://www.dyntaxa.se/] and the R library **dyntaxa**.


## Data Sources
Depending on what questions are being asked there are many different resources available. We focus on biodiversity data 

### Biodiversity record data
There are a large number of available online resources. These include but are not limited to (specific R libraries that connect to these databases are provided in **bold**):

- Artportalen [https://www.artportalen.se/] - Sweden's data portal for biodiversity data 
- Global Biodiversity Information Facility	[http://www.gbif.org/] - International organization aggregating biodiversity data. Contains data from a mixture of sources; curated collections, community science data, ecological research projects etc. **rgbif, spocc** 
- BioCASE	[https://www.biocase.org/] - A European transnational biodiversity repository
- eBird	[http://ebird.org/content/ebird/] - American database of bird observations **auk, rebird,spocc**
- iNaturalist	http://www.inaturalist.org/ - International community science observation repository **spocc**
- Berkeley ecoengine	[https://ecoengine.berkeley.edu] - Access to UC Berkley's Natural history data **spocc**
- VertNet	[http://vertnet.org/] - vertebrate biodiversity collections **rvert, spocc**
- iDigBio	[https://www.idigbio.org/] - Integrated digitise biodiversity collections **ridigbio**
- OBIS	[http://www.iobis.org/] - Ocean biodiversity information system **robis**
- ALA	[http://www.ala.org.au/] - Atlas of living Australia **ALA4r**
- Neotoma [https://www.neotomadb.org/] Palaeoecology databas **neotoma**
- ...

### Taxonomic diversity
To keep track of ever changing taxonomy of species there are different databases that follow different standars.

- dyntaxa [https://www.dyntaxa.se/]
- GBIF backbone [http://www.gbif.org/]
- ...

### Functional diversity
Very broadly functional diversity is the diversity of what organisms do [@petchey_functional_2006]. Such diversity can be direct physical measurements of traits of the organisms involved and / or data summarized from published works. There are databases dedicated to the distribution of scientific data that may be used. Such resources include:

- Dryad [https://datadryad.org/stash]
- TRY: Plant Trait Database [https://www.try-db.org/TryWeb/Home.php]
- Ecological indicator and traits values for Swedish vascular plants[@tyler_ecological_2021] [https://doi.org/10.1016/j.ecolind.2020.106923]
- Vertnet [http://vertnet.org/] 
- ...

### Genetic data bases

Genetic data may be related directly to the samples used, phylogenetic trees generated from some other data set set or some other genetic aspect. Such resources include:  

- BOLD: Barcode Of Life Data system [https://www.boldsystems.org/] Repository of gene sequences
- Genbank. A genetic sequence repository. See [https://www.ncbi.nlm.nih.gov/genbank/] for access details.
- Treebase [https://www.treebase.org/treebase-web/home.html] A data base of phylogenetic trees
- ...


### Environemntal data

There are a number of environmental repositories available. Static data sets for global resources include:

#### Sweden

- Skogstyrelsen [https://www.skogsstyrelsen.se/sjalvservice/karttjanster/geodatatjanster/oppna-data/] Open data supplied by Skogstyrelsen
- Sveriges dataportal [https://www.dataportal.se/] Swedish open data provided by governmental bodies.
- Miljödata MVM [https://miljodata.slu.se/mvm/] - Environmental data from SLU for Sweden

#### Global and European 
- wordclim [https://www.worldclim.org/] Global gridded climate data at various resolutions
- climond [https://www.climond.org/] Global gridded climate data at various resolutions
- soilgrids [https://soilgrids.org/] Global gridded soil data
- Copernicus Land monitoring service [https://land.copernicus.eu/pan-european/corine-land-cover] Land monitoring data from across the EU


