---
title: "The importance of questions and sources of Data"
author: "Charlie Campbell"
date: "03/11/2020"
output: html_document
bibliography: "./Bibliography/Bibliography.bib"
preserve_yaml: FALSE
---

# Questions, Taxonomies and Data

## Questions
Any question to be asked of biodiversity data should be put as simply and succinctly as possible. With the number of different subject areas and techniques used, analyses can quickly become complex.


### Biodiversity data

#### Taxonomic diversity

There are a large number of available online resources. These include but are not limited to (r libraries in **bold**:

- Artportalen [https://www.analysisportal.se/] - Sweden's data portal for biodiversity data 
- Miljödata MVM [https://miljodata.slu.se/mvm/] - Environmental data from SLU for Sweden
- Global Biodiversity Information Facility	[http://www.gbif.org/] - International organisation aggregating biodiversity data.  Contains data from a mixture of sources; curated collections, community science data, ecological research projects etc. **rgbif, spocc**
- BioCASE	[https://www.biocase.org/] - A European transnational biodiversity repository
- eBird	[http://ebird.org/content/ebird/] - American database of bird observations **auk, rebird,spocc**
- iNaturalist	http://www.inaturalist.org/ - International community science observation repository **spocc**
- Berkeley ecoengine	[https://ecoengine.berkeley.edu] - Access to UC Berkley's Natural history data **spocc**
- VertNet	[http://vertnet.org/] - vertebrate biodiversity collections **rvert, spocc**
- iDigBio	[https://www.idigbio.org/] - Integrated digitise biodiversity collections **ridigbio**
- OBIS	[http://www.iobis.org/] - Ocean biodiversity information system **robis**
- ALA	[http://www.ala.org.au/] - Atlas of living Australia **ALA4r**
- Neotoma [https://www.neotomadb.org/] Palaeoecology databas **neotoma**

#### Functional diversity data

Very broadly functional diversity is the diversity of what organisms do [@petchey_functional_2006]. Such diversity can be direct physical measurements of traits of the organisms involved and / or data sumamrised from published works. There are databses dedicated to the distribution of scientific data that may be used. Such resources include:

- Dryad [https://datadryad.org/stash]
- TRY: Plant Trait Database [https://www.try-db.org/TryWeb/Home.php]
- Ecological indicator and traits values for Swedish vascular plants[@tyler_ecological_2021] [https://doi.org/10.1016/j.ecolind.2020.106923]
- Vertnet [http://vertnet.org/] 

#### Genetic data

Genetic data may be related directly to the samples used, phylogenetic trees generated from some other data set set or some other genetic aspect. Such resources include:
- BOLD: Barcode Of Life Data system [https://www.boldsystems.org/] Repository of gene sequences
- Genbank. A genetic sequence repository. See [https://www.ncbi.nlm.nih.gov/genbank/] for access details.
- Treebase [https://www.treebase.org/treebase-web/home.html] A data base of phylogenetic trees

### Environemntal data

There are a number of environmental repositories available. Static data sets for global resources include:

#### Sweden

- Skogstyrelsen [https://www.skogsstyrelsen.se/sjalvservice/karttjanster/geodatatjanster/oppna-data/] Open data supplied by Skogstyrelsen
- Sveriges dataportal [https://www.dataportal.se/] Swedish open data provided by governmental bodies.

#### Global and European 
- wordclim [https://www.worldclim.org/] Global gridded climarte data at various resolutions
- climond [https://www.climond.org/] Global gridded climarte data at various resolutions
- soilgrids [https://soilgrids.org/] Global gridded soil data
- Copernicus Land monitoring servic [https://land.copernicus.eu/pan-european/corine-land-cover] Land monitoring data from across the EU

# References
